### PR TITLE
Added endpoint to get organizer and filter events by organizer id

### PR DESCRIPTION
**Pull request by Udito3**

### CODE REVIEW

**Review by MysticFragilist — DISMISSED** [review]
LGTM! 💯

**Comment by MysticFragilist** [comment]
Il va manquer ton bump tho

**Review by camillebrulotte — DISMISSED** [review]
LGTM !

**Review by camillebrulotte — APPROVED** [review]
LGTM!

**Review by HugoMigner — APPROVED** [review]

**Pull request merged**
